### ISSUE TITLE
Docker image not available to pull

### ISSUE THREAD

**Issue by stmutasa** [yala/OncoServe_Public#1]
As of 7/10/19 the docker image pull request for yala/oncoserve:0.2.1 says repository does not exist.

**Comment by lishen** [comment]
+1

**Comment by t-sanders** [comment]
+1

**Comment by yala** [comment]
For now, the docker image is now only available upon request. We've had some concerns about improper use and so now we request that people reach out to us directly (with an intended use-case) and we'll grant you access to the private dockerhub.

**Comment by yala** [comment]
Docker Image now available. Please reach out directly with your dockerhub id and descrip of study if you haven't already.
